import './globals.css'
import type { Metadata } from 'next'
import SetupProvider from '@/provider/SetupProvider'
import TanstackProvider from '@/provider/TanstackProvider'
import HeroUiProvider from '@/provider/HeroUiProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="light">
      <body>
        <SetupProvider>
          <TanstackProvider>
            <HeroUiProvider>
              <>{children}</>
            </HeroUiProvider>
          </TanstackProvider>
        </SetupProvider>
      </body>
    </html>
  )
}
